// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY
// If you want to change the content of this file, you need to edit
// file '/dictionaries/en.po' and run '.po' extractor
export const events = {
  'events.error.name.invalid': 'The name is not valid',
  'events.error.name.required': 'Please enter your name',
  'events.error.phone.invalid': 'Phone number is not valid',
  'events.error.phone.required': 'Please enter your phone number',
};
