// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY
// If you want to change the content of this file, you need to edit
// file '/dictionaries/ru.po' and run '.po' extractor
export const base = {
  'base.buttons.currentDate': 'Текущая дата',

  'base.buttons.save': 'Сохранить',

  'base.buttons.showVisits': 'Показать визиты',

  'components.atoms.Calendar.month': 'Месяц',
  'components.atoms.Calendar.year': 'Год',

  'components.organisms.Page.title': 'Главная',

  'components.organisms.forms.UserForm.address': 'Адрес',
  'components.organisms.forms.UserForm.city': 'Город',
  'components.organisms.forms.UserForm.mainBlock': 'Основное',
  'components.organisms.forms.UserForm.contactsBlock': 'Контакты',
  'components.organisms.forms.UserForm.locationBlock': 'Местоположение',
  'components.organisms.forms.UserForm.mail': 'Почта',
  'components.organisms.forms.UserForm.name': 'Имя',
  'components.organisms.forms.UserForm.notes': 'Заметки',
  'components.organisms.forms.UserForm.notesBlock': 'О себе',
  'components.organisms.forms.UserForm.phone': 'Телефон',
  'components.organisms.forms.UserForm.specialization': 'Специализация',
  'components.organisms.forms.UserForm.surname': 'Фамилия',
  'components.organisms.forms.UserForm.telegram': 'Телеграм',
  'components.organisms.forms.UserForm.vkontakte': 'ВКонтакте',

  'components.routes.pages.Calendar.noMeetings':
    'На данный день встреч не назначено.',
  'components.routes.pages.Calendar.oneMeeting':
    'В этот день назначена встреча на время:',
  'components.routes.pages.Calendar.severalMeetings':
    'В этот день назначены встречи на время:',
  'components.routes.pages.Calendar.title': 'Календарь',
  'components.routes.pages.Error404.body':
    'Это не та страница, которую вы ищете :(',
  'components.routes.pages.Error404.title': '404 Не найдено',
  'components.routes.pages.Timezone.timezoneDefinition':
    'Выполняется определение текущего часового пояса...',
  'components.routes.pages.Timezone.title': 'Часовой пояс',
  'components.routes.pages.User.notFound': 'Пользователь не найден',
  'components.routes.pages.User.title': 'Профиль пользователя',

  'components.templates.WithHeader.goBack': 'Вернуться на предыдущий экран',

  'constants.ui.months.april': 'Апрель',
  'constants.ui.months.august': 'Август',
  'constants.ui.months.december': 'Декабрь',
  'constants.ui.months.february': 'Февраль',
  'constants.ui.months.january': 'Январь',
  'constants.ui.months.july': 'Июль',
  'constants.ui.months.june': 'Июнь',
  'constants.ui.months.march': 'Март',
  'constants.ui.months.may': 'Май',
  'constants.ui.months.november': 'Ноябрь',
  'constants.ui.months.october': 'Октябрь',
  'constants.ui.months.september': 'Сентябрь',

  'constants.ui.monthsShort.april': 'Апр',
  'constants.ui.monthsShort.august': 'Авг',
  'constants.ui.monthsShort.december': 'Дек',
  'constants.ui.monthsShort.february': 'Фев',
  'constants.ui.monthsShort.january': 'Янв',
  'constants.ui.monthsShort.july': 'Июл',
  'constants.ui.monthsShort.june': 'Июн',
  'constants.ui.monthsShort.march': 'Мар',
  'constants.ui.monthsShort.may': 'Май',
  'constants.ui.monthsShort.november': 'Ноя',
  'constants.ui.monthsShort.october': 'Окт',
  'constants.ui.monthsShort.september': 'Сен',

  'constants.ui.weekdaysShort.friday': 'Пт',
  'constants.ui.weekdaysShort.monday': 'Пн',
  'constants.ui.weekdaysShort.saturday': 'Сб',
  'constants.ui.weekdaysShort.sunday': 'Вс',
  'constants.ui.weekdaysShort.thursday': 'Чт',
  'constants.ui.weekdaysShort.tuesday': 'Вт',
  'constants.ui.weekdaysShort.wednesday': 'Ср',
};
