// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY
// If you want to change the content of this file, you need to edit
// file '/dictionaries/ru.po' and run '.po' extractor
export const events = {
  'events.error.name.invalid': 'Вы указали невалидное имя',
  'events.error.name.required': 'Пожалуйста, укажите ваше имя',
  'events.error.phone.invalid': 'Вы указали невалидный номер телефона',
  'events.error.phone.required': 'Пожалуйста, укажите свой номер телефона',
};
